export const SEED_DATA = {
  columns: [
    { id: 'backlog', title: 'BACKLOG', cardIds: ['TKT-001', 'TKT-005', 'TKT-008'] },
    { id: 'todo', title: 'TO DO', cardIds: ['TKT-002', 'TKT-006'] },
    { id: 'progress', title: 'IN PROGRESS', cardIds: ['TKT-003', 'TKT-009'] },
    { id: 'review', title: 'IN REVIEW', cardIds: ['TKT-004'] },
    { id: 'done', title: 'DONE', cardIds: ['TKT-007', 'TKT-010'] },
  ],
  cards: {
    'TKT-001': {
      id: 'TKT-001',
      title: 'Implement user authentication',
      description: 'Add OAuth2 integration with Google and GitHub providers. This includes setting up callback URLs, token refresh logic, and session management across multiple browser tabs.',
      priority: 'high',
      labels: ['feature', 'backend'],
      dueDate: '2026-02-15',
      createdAt: '2026-01-20T10:00:00Z',
    },
    'TKT-002': {
      id: 'TKT-002',
      title: 'Fix responsive navigation menu',
      description: 'Mobile menu is not working properly on iOS devices. The hamburger icon fails to toggle the drawer and touch events are swallowed by the backdrop overlay.',
      priority: 'critical',
      labels: ['bug', 'frontend', 'urgent'],
      dueDate: '2026-02-01',
      createdAt: '2026-01-21T14:30:00Z',
    },
    'TKT-003': {
      id: 'TKT-003',
      title: 'Design new landing page',
      description: 'Create a modern, conversion-focused landing page with hero section, social proof, and clear CTAs.',
      priority: 'medium',
      labels: ['design', 'feature'],
      dueDate: '2026-02-10',
      createdAt: '2026-01-22T09:15:00Z',
    },
    'TKT-004': {
      id: 'TKT-004',
      title: 'Add unit tests for API endpoints',
      description: 'Cover all REST API endpoints with comprehensive test suite including edge cases and error scenarios.',
      priority: 'medium',
      labels: ['testing', 'backend'],
      dueDate: '2026-02-08',
      createdAt: '2026-01-23T11:45:00Z',
    },
    'TKT-005': {
      id: 'TKT-005',
      title: 'Optimize database queries',
      description: 'Improve performance of slow-running queries in dashboard. The main analytics query takes 4s+ on large datasets.',
      priority: 'low',
      labels: ['backend', 'chore'],
      dueDate: null,
      createdAt: '2026-01-24T16:20:00Z',
    },
    'TKT-006': {
      id: 'TKT-006',
      title: 'Implement dark mode toggle',
      description: 'Add system preference detection and manual toggle for dark theme.',
      priority: 'low',
      labels: ['feature', 'frontend'],
      dueDate: '2026-02-20',
      createdAt: '2026-01-25T13:10:00Z',
    },
    'TKT-007': {
      id: 'TKT-007',
      title: 'Setup CI/CD pipeline',
      description: 'Configure GitHub Actions for automated testing and deployment to staging and production environments.',
      priority: 'high',
      labels: ['backend', 'feature'],
      dueDate: null,
      createdAt: '2026-01-19T10:30:00Z',
    },
    'TKT-008': {
      id: 'TKT-008',
      title: 'Add email notifications',
      description: 'Send email alerts for important user actions like password changes, new logins, and billing updates.',
      priority: 'medium',
      labels: ['feature', 'backend'],
      dueDate: '2026-02-12',
      createdAt: '2026-01-26T15:45:00Z',
    },
    'TKT-009': {
      id: 'TKT-009',
      title: 'Create user dashboard',
      description: 'Build comprehensive dashboard with analytics and user metrics including charts, activity feed, and quick actions.',
      priority: 'high',
      labels: ['feature', 'frontend', 'design'],
      dueDate: '2026-02-05',
      createdAt: '2026-01-27T12:00:00Z',
    },
    'TKT-010': {
      id: 'TKT-010',
      title: 'Update documentation',
      description: 'Update API documentation with new endpoints and examples.',
      priority: 'low',
      labels: ['chore'],
      dueDate: null,
      createdAt: '2026-01-18T08:30:00Z',
    },
  },
  nextTicketNumber: 11,
};
